apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: back
        image: back:1.6
        imagePullPolicy: Never
        ports:
        - containerPort: 3030

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  #type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030