apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: capstone-cluster.deyaa.online
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable    
  cloudProvider: aws
  configBase: s3://capstone-cluster
  dnsZone: deyaa.online
  kubernetesVersion: 1.21.1
  etcdClusters:
  - name: main
    memoryRequest: 100Mi
    cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-west-2c
      name: c
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-west-2c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  #kubernetesVersion: 1.21.4
  masterPublicName: api.capstone-cluster.deyaa.online  
  sshpublickey: ~/.ssh/ida_rsa.pub
  networkID: vpc-8c6f17e4
  networkCIDR: 172.31.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: eu-west-2a
    type: Public
    zone: eu-west-2a
    cidr: 172.31.48.0/20
  - name: eu-west-2b
    type: Public
    zone: eu-west-2b
    cidr: 172.31.64.0/20
  - name: eu-west-2c
    type: Public
    zone: eu-west-2c
    cidr: 172.31.80.0/20
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: capstone-cluster.deyaa.online
  name: master-eu-west-2a
spec:
  machineType: t2.micro
  maxSize: 2
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-2a
  role: Master
  subnets:
  - eu-west-2a
  #- eu-west-2b
  #- eu-west-2c

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: capstone-cluster.deyaa.online
  name: ig1
spec:
  machineType: t2.micro
  maxSize: 3
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: node
  role: Node
  subnets:
  - eu-west-2a
  - eu-west-2b
  - eu-west-2c
