## Docker compose file testing front and back locally
version: "3.8"

services:
  front:
    container_name: front
    image: front:1.8
    volumes:
      - ./frontend/nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 3000:3000

  back:
    container_name: back
    image: back:1.6
    ports:
      - 3030:3030

  #nginx:
  #  container_name: nginx
  #  image: nginx
  #  volumes:
  #    - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
  #  ports: 
  #    - 80:80