##
# Python CircleCI 2.0 configuration file
#
version: 2
workflows:
  flask:
    jobs:
      - build
      - dockerize:
        requires: [build]
      - provision:
        requires: [dockerize]
      - update:
        requires: [provision]
      - validate:
        requires: [update]
      - cleanup:
        requires: [validate]
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: python:3.7.3-stretch

    working_directory: /app

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.ml
            . ~/.ml/bin/activate
            #pip install -r requirements.txt
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      # run lints!
      - run:
          name: run lint
          command: |
            . ~/.ml/bin/activate
            make lint
    
  dockerize:
    machine:
      image: python:3.7.3-stretch
      docker_layer_caching: true
      
