##
# Python CircleCI 2.0 configuration file
#
version: 2.1
workflows:
  flask:
    jobs:
      #- build
      - dockerize
      #    requires: [build]
      #- provision:
      #   requires: [dockerize]
      #- update:
      #   requires: [provision]
      #- validate:
      #   requires: [update]
      #- cleanup:
      #   requires: [validate]

jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: python:3.7.3-stretch

    working_directory: /app

    steps:
      - checkout
      # Download and cache dependencies
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "requirements.txt" }}
#            # fallback to using the latest cache if no exact match is found
#            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            #pip install -r requirements.txt
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
#      - save_cache:
#          paths:
#            - ./venv
#          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lints!
      - run:
          name: run lint
          command: |
            make lint

  dockerize:
    machine: true
      #docker_layer_caching: true
    environment:
      ecr: 135834287615.dkr.ecr.eu-west-2.amazonaws.com
      version: 1.0
    #docker:
    #  - image: python:3.7.3-stretch

    steps:
      - checkout
      #- setup_remote_docker:
      #    version: 19.03.13
      #    #docker_layer_caching: true
      - run:
          name: install aws
          command: sudo apt update && sudo apt install awscli -y
      - run: |
          pass=$(aws ecr get-login-password --region eu-west-2)
          docker login --username AWS --password ${pass} 135834287615.dkr.ecr.eu-west-2.amazonaws.com
          docker build -t ${ecr}/flask:${version} .
          docker push ${ecr}/flask:${version}
